// Central Lamatic node schema registry (provided by user)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ALL_SCHEMAS: Record<string, any> = {
  "ImageGenNode": {
    "type": "object",
    "properties": {
      "nodeId": { "type": "string", "required": true },
      "nodeType": { "type": "string", "required": true },
      "nodeName": { "type": "string", "required": true },
      "needs": { "type": "array", "items": { "type": "string" } },
      "values": {
        "type": "object",
        "required": true,
        "properties": {
          "imageGenModelName": {
            "type": "object",
            "required": true,
            "properties": {
              "credentialId": { "type": "string", "required": true },
              "credential_name": { "type": "string", "required": true },
              "model_name": { "type": "string", "required": true },
              "provider_name": { "type": "string", "required": true },
              "type": { "type": "string", "required": true }
            },
            "additionalProperties": true
          },
          "prompts": {
            "type": "array",
            "required": true,
            "items": {
              "type": "object",
              "properties": {
                "content": { "type": "string", "required": true },
                "id": { "type": "string", "required": true },
                "role": { "type": "string", "required": true }
              },
              "additionalProperties": true
            }
          }
        },
        "additionalProperties": true
      }
    },
    "additionalProperties": true
  },
  "IndexNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "duplicateOperation": { "type": "string", "required": true }, "embeddingModelName": { "type": "object" }, "generativeModelName": { "type": "object" }, "metadataField": { "type": "string", "required": true }, "primaryKeys": { "type": "array", "required": true, "items": { "type": "string" } }, "vectorDB": { "type": "string", "required": true }, "vectorsField": { "type": "string", "required": true }, "webhookURL": { "type": "string" } }, "additionalProperties": true } }, "additionalProperties": true },
  "InstructorLLMNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "attachments": { "type": "string", "required": true }, "generativeModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string", "required": true }, "credential_name": { "type": "string", "required": true }, "model_name": { "type": "string", "required": true }, "provider_name": { "type": "string", "required": true }, "type": { "type": "string", "required": true } }, "additionalProperties": true }, "memories": { "type": "string", "required": true }, "messages": { "type": "string", "required": true }, "prompts": { "type": "array", "required": true, "items": { "type": "object", "properties": { "content": { "type": "string", "required": true }, "id": { "type": "string", "required": true }, "role": { "type": "string", "required": true } }, "additionalProperties": true } }, "schema": { "type": "string", "required": true }, "tools": { "type": "array", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "LLMNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "attachments": { "type": "string", "required": true }, "credentials": { "type": "string", "required": true }, "generativeModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string", "required": true }, "credential_name": { "type": "string", "required": true }, "model_name": { "type": "string", "required": true }, "provider_name": { "type": "string", "required": true }, "type": { "type": "string", "required": true } }, "additionalProperties": true }, "memories": { "type": "string", "required": true }, "messages": { "type": "string", "required": true }, "prompts": { "type": "array", "required": true, "items": { "type": "object", "properties": { "content": { "type": "string", "required": true }, "id": { "type": "string", "required": true }, "role": { "type": "string", "required": true } }, "additionalProperties": true } }, "tools": { "type": "array", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "RAGNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "certainty": { "type": "string", "required": true }, "embeddingModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string", "required": true }, "credential_name": { "type": "string", "required": true }, "model_name": { "type": "string", "required": true }, "provider_name": { "type": "string", "required": true }, "type": { "type": "string", "required": true } }, "additionalProperties": true }, "filters": { "type": "string", "required": true }, "generativeModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string", "required": true }, "credential_name": { "type": "string", "required": true }, "model_name": { "type": "string", "required": true }, "provider_name": { "type": "string", "required": true }, "type": { "type": "string", "required": true } }, "additionalProperties": true }, "limit": { "type": "integer", "required": true }, "memories": { "type": "string", "required": true }, "messages": { "type": "string", "required": true }, "prompts": { "type": "array", "required": true, "items": { "type": "object", "properties": { "content": { "type": "string", "required": true }, "id": { "type": "string", "required": true }, "role": { "type": "string", "required": true } }, "additionalProperties": true } }, "queryField": { "type": "string", "required": true }, "vectorDB": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "addNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "description": "Configuration values for the node. Always an empty object for addNode." } }, "additionalProperties": true },
  "agentClassifierNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "classifier": { "type": "array", "items": { "type": "object", "properties": { "label": { "type": "string" }, "value": { "type": "string" } } } }, "modes": { "type": "array" }, "values": { "type": "object", "required": true, "properties": { "classifier": { "type": "array", "required": true, "items": { "type": "object", "properties": { "label": { "type": "string", "required": true }, "value": { "type": "string", "required": true } }, "additionalProperties": true } }, "generativeModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string", "required": true }, "credential_name": { "type": "string", "required": true }, "model_name": { "type": "string", "required": true }, "params": { "type": "object" }, "provider_name": { "type": "string", "required": true }, "type": { "type": "string", "required": true } }, "additionalProperties": true }, "prompts": { "type": "array", "required": true, "items": { "type": "object", "properties": { "content": { "type": "string", "required": true }, "id": { "type": "string", "required": true }, "role": { "type": "string", "required": true } }, "additionalProperties": true } } }, "additionalProperties": true } }, "additionalProperties": true },
  "agentLoopEndNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "connections": { "type": "array", "items": { "type": "object", "properties": { "condition": { "type": "string" }, "invisible": { "type": "boolean" }, "type": { "type": "string" }, "value": { "type": "string" } } } }, "values": { "type": "object", "required": true, "properties": { "connectedTo": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "agentNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "connections": { "type": "array", "items": { "type": "object", "properties": { "condition": { "type": "string" }, "invisible": { "type": "boolean" }, "type": { "type": "string" }, "value": { "type": "string" } } } }, "values": { "type": "object", "required": true, "properties": { "agents": { "type": "array", "required": true, "items": { "type": "object", "properties": { "description": { "type": "string", "required": true }, "name": { "type": "string", "required": true }, "schema": { "type": "string", "required": true } }, "additionalProperties": true } }, "connectedTo": { "type": "string", "required": true }, "generativeModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string", "required": true }, "credential_name": { "type": "string", "required": true }, "model_name": { "type": "string", "required": true }, "provider_name": { "type": "string", "required": true }, "type": { "type": "string", "required": true } }, "additionalProperties": true }, "maxIterations": { "type": "integer", "required": true }, "messages": { "type": "string", "required": true }, "prompts": { "type": "array", "required": true, "items": { "type": "object", "properties": { "content": { "type": "string", "required": true }, "id": { "type": "string", "required": true }, "role": { "type": "string", "required": true } }, "additionalProperties": true } }, "stopWord": { "type": "string", "required": true }, "tools": { "type": "array", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "apiNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "body": { "type": "string", "required": true }, "headers": { "type": "string", "required": true }, "method": { "type": "string", "required": true }, "retries": { "type": "string", "required": true }, "retry_deplay": { "type": "string", "required": true }, "url": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "branchNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "branches": { "type": "array", "items": { "type": "object", "properties": { "label": { "type": "string" }, "value": { "type": "string" } } } }, "modes": { "type": "array" }, "values": { "type": "object", "required": true, "properties": { "branches": { "type": "array", "required": true, "items": { "type": "object", "properties": { "label": { "type": "string", "required": true }, "value": { "type": "string", "required": true } }, "additionalProperties": true } } }, "additionalProperties": true } }, "additionalProperties": true },
  "chatResponseNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "content": { "type": "string", "required": true }, "references": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "chatTriggerNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "values": { "type": "object", "required": true, "properties": { "chat": { "type": "string", "required": true }, "chatConfig": { "type": "object", "required": true, "properties": { "agentMessageBgColor": { "type": "string" }, "agentMessageTextColor": { "type": "string" }, "botName": { "type": "string" }, "displayMode": { "type": "string" }, "errorMessage": { "type": "string" }, "greetingMessage": { "type": "string" }, "headerBgColor": { "type": "string" }, "headerTextColor": { "type": "string" }, "hideBranding": { "type": "boolean" }, "imageUrl": { "type": "string" }, "placeholder": { "type": "string" }, "policyUrl": { "type": "string" }, "position": { "type": "string" }, "primaryColor": { "type": "string" }, "showAdvancedColors": { "type": "boolean" }, "showEmojiButton": { "type": "boolean" }, "suggestionBgColor": { "type": "string" }, "suggestionTextColor": { "type": "string" }, "suggestions": { "type": "array" }, "userMessageBgColor": { "type": "string" }, "userMessageTextColor": { "type": "string" } }, "additionalProperties": true }, "domains": { "type": "array", "required": true, "items": { "type": "string" } } }, "additionalProperties": true } }, "additionalProperties": true },
  "chunkNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "chunkField": { "type": "string", "required": true }, "chunkingType": { "type": "string", "required": true }, "numOfChars": { "type": "integer", "required": true }, "overlapChars": { "type": "integer", "required": true }, "separators": { "type": "array", "required": true, "items": { "type": "string" } } }, "additionalProperties": true } }, "additionalProperties": true },
  "codeNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "code": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "conditionNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "condition": { "type": "array", "items": { "type": "object", "properties": { "label": { "type": "string" }, "value": { "type": "string" } } } }, "modes": { "type": "array" }, "values": { "type": "object", "required": true, "properties": { "conditions": { "type": "array", "required": true, "items": { "type": "object", "properties": { "condition": { "type": "object", "required": true }, "label": { "type": "string", "required": true }, "value": { "type": "string", "required": true } }, "additionalProperties": true } } }, "additionalProperties": true } }, "additionalProperties": true },
  "extractFromFileNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "comment": { "type": "string", "required": true }, "delimiter": { "type": "string", "required": true }, "discardUnmappedColumns": { "type": "boolean", "required": true }, "encodeAsBase64": { "type": "boolean", "required": true }, "encoding": { "type": "string", "required": true }, "fileUrl": { "type": "string", "required": true }, "format": { "type": "string", "required": true }, "headers": { "type": "boolean", "required": true }, "ignoreEmpty": { "type": "boolean", "required": true }, "joinPages": { "type": "boolean", "required": true }, "ltrim": { "type": "boolean", "required": true }, "maxRows": { "type": "string", "required": true }, "password": { "type": "string", "required": true }, "quote": { "type": "string", "required": true }, "returnRawText": { "type": "boolean", "required": true }, "rtrim": { "type": "boolean", "required": true }, "skipRows": { "type": "string", "required": true }, "trim": { "type": "boolean", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "firecrawlNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "allowBackwardLinks": { "type": "boolean", "required": true }, "allowExternalLinks": { "type": "boolean", "required": true }, "changeTracking": { "type": "boolean", "required": true }, "crawlDepth": { "type": "integer", "required": true }, "crawlLimit": { "type": "integer", "required": true }, "crawlSubPages": { "type": "boolean", "required": true }, "credentials": { "type": "string", "required": true }, "delay": { "type": "integer", "required": true }, "excludePath": { "type": "array", "required": true }, "excludeTags": { "type": "array", "required": true }, "ignoreQueryParameters": { "type": "boolean", "required": true }, "ignoreSitemap": { "type": "boolean", "required": true }, "includePath": { "type": "array", "required": true }, "includeSubdomains": { "type": "boolean", "required": true }, "includeTags": { "type": "array", "required": true }, "limit": { "type": "integer", "required": true }, "maxDiscoveryDepth": { "type": "integer", "required": true }, "mobile": { "type": "boolean", "required": true }, "mode": { "type": "string", "required": true }, "onlyMainContent": { "type": "boolean", "required": true }, "search": { "type": "string", "required": true }, "sitemapOnly": { "type": "boolean", "required": true }, "skipTlsVerification": { "type": "boolean", "required": true }, "timeout": { "type": "integer", "required": true }, "url": { "type": "string", "required": true }, "urls": { "type": "string", "required": true }, "waitFor": { "type": "integer", "required": true }, "webhook": { "type": "string", "required": true }, "webhookEvents": { "type": "array", "required": true, "items": { "type": "string" } }, "webhookHeaders": { "type": "string", "required": true }, "webhookMetadata": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "flowNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "flowId": { "type": "string", "required": true }, "requestInput": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "forLoopEndNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "connections": { "type": "array", "items": { "type": "object", "properties": { "condition": { "type": "string" }, "invisible": { "type": "boolean" }, "type": { "type": "string" }, "value": { "type": "string" } } } }, "values": { "type": "object", "required": true, "properties": { "connectedTo": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "forLoopNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "connections": { "type": "array", "items": { "type": "object", "properties": { "condition": { "type": "string" }, "invisible": { "type": "boolean" }, "type": { "type": "string" }, "value": { "type": "string" } } } }, "values": { "type": "object", "required": true, "properties": { "connectedTo": { "type": "string", "required": true }, "endValue": { "type": "string", "required": true }, "increment": { "type": "string", "required": true }, "initialValue": { "type": "string", "required": true }, "iterateOver": { "type": "string", "required": true }, "iteratorValue": { "type": "string", "required": true }, "wait": { "type": "integer", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "fullTextSearchNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "autocut": { "type": "string", "required": true }, "boostProperties": { "type": "boolean", "required": true }, "filters": { "type": "string", "required": true }, "limit": { "type": "string", "required": true }, "searchQuery": { "type": "string", "required": true }, "vectorDB": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "gmailNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "action": { "type": "string", "required": true }, "bcc": { "type": "string", "required": true }, "body": { "type": "string", "required": true }, "cc": { "type": "array", "required": true }, "credentials": { "type": "string", "required": true }, "from_user": { "type": "string", "required": true }, "is_html": { "type": "boolean", "required": true }, "max_results": { "type": "integer", "required": true }, "recipient_email": { "type": "string", "required": true }, "subject": { "type": "string", "required": true }, "to_user": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "googleDriveNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "credentials": { "type": "string", "required": true }, "cronExpression": { "type": "string", "required": true }, "folderUrl": { "type": "string", "required": true }, "globs": { "type": "array", "required": true, "items": { "type": "string" } }, "syncMode": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "googleSheetsNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "batchSize": { "type": "string", "required": true }, "credentials": { "type": "string", "required": true }, "cronExpression": { "type": "string", "required": true }, "namesConversion": { "type": "string", "required": true }, "sheetName": { "type": "string", "required": true }, "spreadSheetLink": { "type": "string", "required": true }, "syncMode": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "graphqlNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "advance_schema": { "type": "string", "required": true }, "responeType": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "graphqlResponseNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "headers": { "type": "string", "required": true }, "outputMapping": { "type": "string", "required": true }, "retries": { "type": "string", "required": true }, "retry_delay": { "type": "string", "required": true }, "webhookUrl": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "hybridSearchNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "alpha": { "type": "string", "required": true }, "autocut": { "type": "string", "required": true }, "boostProperties": { "type": "boolean", "required": true }, "certainty": { "type": "string", "required": true }, "embeddingModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string" }, "credential_name": { "type": "string" }, "model_name": { "type": "string" }, "provider_name": { "type": "string" }, "type": { "type": "string" } }, "additionalProperties": true }, "filters": { "type": "string", "required": true }, "fusionType": { "type": "string", "required": true }, "limit": { "type": "string", "required": true }, "searchQuery": { "type": "string", "required": true }, "vectorDB": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "mcpNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "attachments": { "type": "string", "required": true }, "credentials": { "type": "string", "required": true }, "generativeModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string" }, "credential_name": { "type": "string" }, "model_name": { "type": "string" }, "provider_name": { "type": "string" }, "type": { "type": "string" } }, "additionalProperties": true }, "memories": { "type": "string", "required": true }, "messages": { "type": "string", "required": true }, "promptTemplate": { "type": "string", "required": true }, "selectedTools": { "type": "array", "required": true, "items": { "type": "string" } } }, "additionalProperties": true } }, "additionalProperties": true },
  "memoryNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "embeddingModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string" }, "credential_name": { "type": "string" }, "model_name": { "type": "string" }, "provider_name": { "type": "string" }, "type": { "type": "string" } }, "additionalProperties": true }, "generativeModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string" }, "credential_name": { "type": "string" }, "model_name": { "type": "string" }, "provider_name": { "type": "string" }, "type": { "type": "string" } }, "additionalProperties": true }, "memoryCollection": { "type": "string", "required": true }, "memoryValue": { "type": "array", "required": true, "items": { "type": "object", "properties": { "content": { "type": "string" }, "role": { "type": "string" } } } }, "metadata": { "type": "string", "required": true }, "sessionId": { "type": "string", "required": true }, "uniqueId": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "memoryRetrieveNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "embeddingModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string" }, "credential_name": { "type": "string" }, "model_name": { "type": "string" }, "provider_name": { "type": "string" }, "type": { "type": "string" } }, "additionalProperties": true }, "filters": { "type": "string", "required": true }, "limit": { "type": "string", "required": true }, "memoryCollection": { "type": "string", "required": true }, "searchQuery": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "multiModalLLMNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "attachments": { "type": "string", "required": true }, "generativeModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string", "required": true }, "credential_name": { "type": "string", "required": true }, "model_name": { "type": "string", "required": true }, "params": { "type": "object" }, "provider_name": { "type": "string", "required": true }, "type": { "type": "string", "required": true } }, "additionalProperties": true }, "memories": { "type": "string", "required": true }, "messages": { "type": "string", "required": true }, "prompts": { "type": "array", "required": true, "items": { "type": "object", "properties": { "content": { "type": "string", "required": true }, "id": { "type": "string", "required": true }, "role": { "type": "string", "required": true } }, "additionalProperties": true } }, "tools": { "type": "array", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "n8nNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "credentials": { "type": "string", "required": true }, "workflowId": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "onedriveNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "credentials": { "type": "string", "required": true }, "cronExpression": { "type": "string", "required": true }, "days_to_sync_if_history_is_full": { "type": "string", "required": true }, "drive_name": { "type": "string", "required": true }, "folder_path": { "type": "string", "required": true }, "globs": { "type": "array", "required": true, "items": { "type": "string" } }, "search_scope": { "type": "string", "required": true }, "start_date": { "type": "string", "required": true }, "strategy": { "type": "string", "required": true }, "syncMode": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "postgresNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "credentials": { "type": "string", "required": true }, "action": { "type": "string" }, "query": { "type": "string" }, "cronExpression": { "type": "string" }, "schemas": { "type": "string" }, "syncMode": { "type": "string" }, "tables": { "type": "string" } }, "additionalProperties": true } }, "additionalProperties": true },
  "s3Node": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "values": { "type": "object", "required": true, "properties": { "bucket": { "type": "string", "required": true }, "credentials": { "type": "string", "required": true }, "cronExpression": { "type": "string", "required": true }, "days_to_sync_if_history_is_full": { "type": "string", "required": true }, "globs": { "type": "array", "required": true, "items": { "type": "string" } }, "start_date": { "type": "string", "required": true }, "strategy": { "type": "string", "required": true }, "syncMode": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "searchNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "certainty": { "type": "string", "required": true }, "embeddingModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string", "required": true }, "credential_name": { "type": "string", "required": true }, "model_name": { "type": "string", "required": true }, "provider_name": { "type": "string", "required": true }, "type": { "type": "string", "required": true } }, "additionalProperties": true }, "filters": { "type": "string", "required": true }, "limit": { "oneOf": [ { "type": "integer" }, { "type": "string" } ], "required": true }, "searchQuery": { "type": "string", "required": true }, "vectorDB": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "searchResponseNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "breadcrumpsField": { "type": "string", "required": true }, "content": { "type": "string", "required": true }, "group": { "type": "string", "required": true }, "link": { "type": "string", "required": true }, "referenceLink": { "type": "string", "required": true }, "referenceText": { "type": "string", "required": true }, "tab": { "type": "string", "required": true }, "title": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "searchTriggerNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "domains": { "type": "array", "required": true, "items": { "type": "string" } }, "search": { "type": "string", "required": true }, "searchConfig": { "type": "object", "required": true, "properties": { "enableGrouping": { "type": "boolean" }, "hideBranding": { "type": "boolean" }, "linkTarget": { "type": "string" }, "primaryColor": { "type": "string" }, "searchDebounce": { "type": "integer" }, "searchPlaceholderText": { "type": "string" }, "secondaryColor": { "type": "string" }, "showAllTab": { "type": "boolean" }, "showEscapeHelperText": { "type": "boolean" }, "showNavHelperText": { "type": "boolean" }, "staticTabs": { "type": "array" } }, "additionalProperties": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "sharepointNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "credentials": { "type": "string", "required": true }, "cronExpression": { "type": "string", "required": true }, "days_to_sync_if_history_is_full": { "type": "string", "required": true }, "folder_path": { "type": "string", "required": true }, "globs": { "type": "array", "required": true, "items": { "type": "string" } }, "search_scope": { "type": "string", "required": true }, "site_url": { "type": "string", "required": true }, "start_date": { "type": "string", "required": true }, "strategy": { "type": "string", "required": true }, "syncMode": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "slackNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "credentials": { "type": "string", "required": true }, "channelName": { "type": "string", "required": true }, "action": { "type": "string" }, "text": { "type": "string" }, "command": { "type": "string" }, "immediateResponseData": { "type": "string" } }, "additionalProperties": true } }, "additionalProperties": true },
  "teamsNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "credentials": { "type": "string", "required": true }, "conversationType": { "type": "string", "required": true }, "channelId": { "type": "string", "required": true }, "chatId": { "type": "string", "required": true }, "teamId": { "type": "string", "required": true }, "channelMessageId": { "type": "string" }, "channelOperation": { "type": "string" }, "chatOperation": { "type": "string" }, "includePoweredBy": { "type": "boolean" }, "message": { "type": "string" } }, "additionalProperties": true } }, "additionalProperties": true },
  "variablesNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "mapping": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "vectorNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "action": { "type": "string", "required": true }, "duplicateOperation": { "type": "string", "required": true }, "filters": { "type": "string", "required": true }, "limit": { "type": "integer", "required": true }, "metadataField": { "type": "string", "required": true }, "primaryKeys": { "oneOf": [ { "type": "array", "items": { "type": "string" } }, { "type": "string" } ], "required": true }, "vectorDB": { "type": "string", "required": true }, "vectorsField": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "vectorizeNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "embeddingModelName": { "type": "object", "required": true, "properties": { "credentialId": { "type": "string", "required": true }, "credential_name": { "type": "string", "required": true }, "model_name": { "type": "string", "required": true }, "provider_name": { "type": "string", "required": true }, "type": { "type": "string", "required": true } }, "additionalProperties": true }, "generativeModelName": { "type": "object", "required": true }, "inputText": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "waitNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "seconds": { "type": "integer", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "webSearchNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "modes": { "type": "object" }, "values": { "type": "object", "required": true, "properties": { "country": { "type": "string", "required": true }, "credentials": { "type": "string", "required": true }, "dateRange": { "type": "string", "required": true }, "language": { "type": "string", "required": true }, "location": { "type": "string", "required": true }, "page": { "oneOf": [ { "type": "integer" }, { "type": "string" } ], "required": true }, "query": { "type": "string", "required": true }, "results": { "oneOf": [ { "type": "integer" }, { "type": "string" } ], "required": true }, "type": { "type": "string", "required": true } }, "additionalProperties": true } }, "additionalProperties": true },
  "webhookTriggerNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "values": { "type": "object", "required": true } }, "additionalProperties": true },
  "airtableNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "baseId": { "type": "string" }, "tableName": { "type": "string" }, "operation": { "type": "string" }, "fields": { "type": "object" }, "options": { "type": "object" }, "credentials": { "type": "string" } }, "additionalProperties": true } }, "additionalProperties": true },
  "notionNode": { "type": "object", "properties": { "nodeId": { "type": "string", "required": true }, "nodeType": { "type": "string", "required": true }, "nodeName": { "type": "string", "required": true }, "needs": { "type": "array", "items": { "type": "string" } }, "values": { "type": "object", "required": true, "properties": { "operation": { "type": "string" }, "resource": { "type": "string" }, "databaseId": { "type": "string" }, "pageId": { "type": "string" }, "properties": { "type": "object" }, "options": { "type": "object" }, "credentials": { "type": "string" } }, "additionalProperties": true } }, "additionalProperties": true }
};


